<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 fixedio.glb --transform
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'
  const dracoLoader = useDraco()
  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/models/fixedio-transformed.glb', {
    dracoLoader
})
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
  scale={[ 1.05, 1, 1 ]}
  position={[ 0.4332, -1.1902, 0 ]}
  rotation={[ -0.3396, 0.8856, 0.2602 ]}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Plane002.geometry}
      material={gltf.materials['Material.001']}
      material.metalness={0.2717}
      position={[ -0.1, -0.2, 0 ]}
      scale={[ 1, 1, 1 ]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane_1.geometry}
      material={gltf.materials['Material.002']}
      material.metalness={0.7283}
      material.roughness={1}
      material.emissiveIntensity={2}
      material.opacity={1}
      scale={[ 1, 1, 1 ]}
      position={[ 0, -0.015, 0 ]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane_2.geometry}
      material={gltf.materials['Material.003']}
      material.metalness={1}
      material.emissiveIntensity={2}
      material.roughness={1}
      scale={[ 1.3, 1.2, 1 ]}
      position={[ 0, -0.13, 0 ]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane_3.geometry}
      material={gltf.materials['Material.004']}
      material.roughness={1}
      material.metalness={1}
      material.emissiveIntensity={2}
      scale={[ 1.45, 1, 1.3 ]}
      position={[ 0.26, -0.18, 0.19 ]}
      rotation={[ -0.1065, 0.0017, 0 ]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane_4.geometry}
      material={gltf.materials['Material.005']}
      material.roughness={1}
      material.metalness={1}
      scale={[ 1.7, 1.3, 1 ]}
      position={[ 0.51, 0, 0 ]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
