<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 test4.glb --transform
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'
  const dracoLoader = useDraco()
  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/models/test4-transformed.glb', {
    dracoLoader
})
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
  scale={[ 1.05, 1, 1 ]}
  position={[ 0.5432, -1.5646, 0 ]}
  rotation={[ -0.4269, 0.7809, 0.3126 ]}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Plane002.geometry}
      material={gltf.materials['Material.001']}
      material.transparent={false}
      material.metalness={0.7717}
      material.roughness={0.6413}
      rotation={[ -0.0384, 0, 0 ]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane_1.geometry}
      material={gltf.materials['Material.002']}
      material.metalness={1}
      material.roughness={1}
      material.emissiveIntensity={1.4}
      position={[ 0, -0.1, 0 ]}
      scale={[ 1, 1, 1 ]}
      rotation={[ -0.0192, 0, 0 ]}
      material.transparent
    />
    <T.Mesh
      geometry={gltf.nodes.Plane_2.geometry}
      material={gltf.materials['Material.003']}
      material.roughness={1}
      material.metalness={1}
      material.emissiveIntensity={1.1}
      position={[ -0.2, -0.02, 0 ]}
      scale={[ 1.15, 1.1, 1 ]}
      material.transparent
      material.opacity={1}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane_3.geometry}
      material={gltf.materials['Material.004']}
      material.roughness={1}
      material.metalness={1}
      material.envMapIntensity={1}
      material.emissiveIntensity={1.1}
      position={[ -0.2, -0.4, 0 ]}
      scale={[ 1.65, 1.15, 1 ]}
      material.transparent
    />
    <T.Mesh
      geometry={gltf.nodes.Plane_4.geometry}
      material={gltf.materials['Material.005']}
      material.roughness={1}
      material.metalness={1}
      material.emissiveIntensity={0}
      position={[ -0.2, -0.7, 0 ]}
      scale={[ 1.3, 1.1, 1 ]}
      material.alphaTest={0.9}
      material.alphaHash
      material.transparent
      material.opacity={1}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane_5.geometry}
      material={gltf.materials['Material.006']}
      material.roughness={0.2609}
      material.metalness={0}
      material.emissiveIntensity={0.56}
      position={[ -4.4, 9.1, 0 ]}
      material.color="#daaf78"
      material.emissive="#edf4e3"
      material.transparent
      material.opacity={1}
      material.clipIntersection={false}
      rotation={[ -0.0349, -0.3176, 0 ]}
      scale={[ 1.6, 1, 1 ]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane_6.geometry}
      material={gltf.materials.Material}
      material.roughness={0}
      material.metalness={1}
      material.emissiveIntensity={1.1}
      material.transparent
      material.opacity={1}
      rotation={[ 0.1047, 0, 0 ]}
      position={[ 0.1, 0.2, -0.4 ]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
