<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 test2.glb --transform
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'
  const dracoLoader = useDraco()
  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/models/test2-transformed.glb', {
  dracoLoader
})
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
  position={[ 1.9889, 5.3239, -0.229 ]}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.reconstruction003.geometry}
      material={gltf.materials['Material.006']}
      position={[0, -0.9, 0]}
      material.shadowSide={1}
      material.side={1}
      material.emissiveIntensity={3.1}
      material.metalness={1}
      material.roughness={1}
      material.alphaHash
      material.wireframe={false}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
