<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 test2.glb --transform
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'
  const dracoLoader = useDraco()
  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/models/test2-transformed.glb', {
  dracoLoader
})
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
  scale={[ 1.05, 1, 1 ]}
  position={[ 0.4332, -1.1902, 0 ]}
  rotation={[ -0.3396, 0.8856, 0.2602 ]}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.reconstruction003.geometry}
      material={gltf.materials['Material.006']}
      position={[0, -0.9, 0]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
